
-- ============================================================
-- 44 SHOTS — WHAT-HAPPENED LAYER
-- games: a game session (one per actual game played)
-- game_observations: each scorer's independent log of that game
-- shot_events: individual shot/goal records logged by a scorer
-- consensus_events: reconciled "truth" from multiple observations
-- ============================================================

-- A game is the canonical event. It exists once.
-- The first scorer to start logging a game creates it; others join it.
create table public.games (
  id uuid primary key default gen_random_uuid(),
  goalie_id uuid not null references public.goalies(id) on delete cascade,
  team_id uuid references public.teams(id) on delete set null,
  game_date date not null,
  opponent text,
  we_are text not null default 'home' check (we_are in ('home','away')),
  final_score_for integer,
  final_score_against integer,
  status text not null default 'in_progress' check (status in ('in_progress','complete','reconciled','disputed')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  reconciled_at timestamptz
);

create index games_goalie_idx on public.games(goalie_id);
create index games_team_date_idx on public.games(team_id, game_date desc);
create index games_status_idx on public.games(status);

-- A game_observation is one scorer's full log of one game.
-- Multiple observations per game = multi-observer consensus input.
create table public.game_observations (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  scorer_user_id uuid not null references public.profiles(id) on delete cascade,
  scorer_trust_at_time numeric(4,3) not null,
  device_id text,                  -- optional device fingerprint
  submitted_at timestamptz not null default now(),
  unique (game_id, scorer_user_id)  -- one observation per scorer per game
);

create index game_obs_game_idx on public.game_observations(game_id);
create index game_obs_scorer_idx on public.game_observations(scorer_user_id);

-- Individual shot events as logged by a single scorer.
-- These are the RAW observations. Consensus reconciliation reads from here.
create table public.shot_events (
  id uuid primary key default gen_random_uuid(),
  observation_id uuid not null references public.game_observations(id) on delete cascade,
  -- Game context
  period integer not null check (period between 1 and 5),
  game_state text not null default '5v5' check (game_state in ('5v5','pp','pk','4v4','3v3','en')),
  game_clock_seconds integer,      -- optional, seconds remaining in period
  -- Spatial
  rink_x numeric(5,4) check (rink_x between 0 and 1),     -- normalized 0-1
  rink_y numeric(5,4) check (rink_y between 0 and 1),
  net_zone integer check (net_zone between 1 and 9),       -- 1-9 grid, null if not a goal
  -- Type
  for_or_against text not null check (for_or_against in ('for','against')),
  outcome text not null check (outcome in ('goal','save','miss','block','wide','post')),
  shot_modifier text check (shot_modifier in ('rebound','wrap','tip','one_timer','breakaway','penalty_shot')),
  linked_to_event_id uuid references public.shot_events(id) on delete set null,
  -- Audit
  client_event_id text,            -- the client's local UUID, for idempotency
  logged_at timestamptz not null default now()
);

create index shot_events_obs_idx on public.shot_events(observation_id);
create index shot_events_outcome_idx on public.shot_events(outcome);

-- consensus_events: the reconciled "ground truth" for a game.
-- Generated by the reconciliation function from shot_events across observations.
create table public.consensus_events (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  -- Same shape as shot_events but represents the agreed-upon truth
  period integer not null,
  game_state text not null,
  game_clock_seconds integer,
  rink_x numeric(5,4),
  rink_y numeric(5,4),
  net_zone integer,
  for_or_against text not null,
  outcome text not null,
  shot_modifier text,
  -- Reconciliation metadata
  observer_count integer not null,    -- how many scorers logged this event
  agreement_score numeric(4,3) not null, -- 0-1, how strongly observers agreed
  contributing_event_ids uuid[] not null, -- which shot_events fed into this
  is_disputed boolean not null default false, -- true if observers disagreed enough to flag
  reconciled_at timestamptz not null default now()
);

create index consensus_events_game_idx on public.consensus_events(game_id);
create index consensus_events_outcome_idx on public.consensus_events(outcome);
create index consensus_events_disputed_idx on public.consensus_events(is_disputed) where is_disputed = true;
